### ISSUE TITLE
Undefined is not removed from types when passing a default value

### ISSUE THREAD

**Issue by targos** [adonisjs/env#19]
## Package version
v2.0.5

## Node.js and npm version
Node.js 14, npm 6

## Sample Code (to reproduce the issue)

```ts
// in env.ts
import Env from '@ioc:Adonis/Core/Env';

export default Env.rules({
  OPTIONAL_STRING: Env.schema.string.optional(),
});

// in contracts/env.ts
declare module '@ioc:Adonis/Core/Env' {
  type CustomTypes = typeof import('../env').default;
  interface EnvTypes extends CustomTypes {}
}

// in some other file
import Env from '@ioc:Adonis/Core/Env';

const value = Env.get('OPTIONAL_STRING', 'defaultValue');
type ValueType = typeof value; // string | undefined
```

`ValueType` should be `string` because of the default value. This is important to avoid errors when passing the value returned by `Env.get()` to a function that requires a string.
Additionally, I think the typings should only allow to pass a default value if the key was declared as optional.

**Comment by thetutlage** [comment]
Yup, it should not be `undefined`. Can you please create a PR to fix the behaviour? 

> Additionally, I think the typings should only allow to pass a default value if the key was declared as optional.
Agree

**Comment by thetutlage** [comment]
Closed by https://github.com/adonisjs/env/pull/22
