### ISSUE TITLE
Report all environment failed validations at once

### ISSUE THREAD

**Issue by targos** [adonisjs/env#20]
Currently, if multiple environment variables fail the validation, only the first one is reported. Then, after fixing it, one has to restart the server and be notified of the next failed validation, etc.

I think it would be more user-friendly to collect and report all env validation errors at once.

**Comment by thetutlage** [comment]
Cool. We can collect all and report them together. I am happy to accept the PR 🙂

**Comment by targos** [comment]
Waiting for https://github.com/adonisjs/env/pull/23

**Comment by thetutlage** [comment]
I am still not 100% sure on best to display multiple exceptions together. If we raise one exception and concatenate the error messages, then we will not be able to leverage error codes properly since different errors have different error codes

**Comment by thetutlage** [comment]
Closing, until a good idea strikes to merge all errors together
