### ISSUE TITLE
Include value of environment variable in error output

### ISSUE THREAD

**Issue by targos** [adonisjs/env#21]
In my case, `NODE_ENV` was equal to "test" because the app was booted in test mode. I needed some time to find that out because my `.env` was correct (with "development") and the error did not include the actual value:

```
Exception: E_INVALID_ENV_VALUE: Value for environment variable "NODE_ENV" must be one of "development,production"
```

**Comment by thetutlage** [comment]
Yup, will be beneficial to do that. Again, can you please create a PR for same?
