### ISSUE TITLE
Unable to escape single sequences

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/env#25]
### Discussed in https://github.com/adonisjs/core/discussions/2858

The single `$` sequences are not escaped when using the escape slash '\'. For example:

```
PASSWORD=pa\$word
```

Return 

```
pas$
```

Expected

```
pas$word
```

**Comment by varun-nambiar** [comment]
Hey,
I have created a pull request here - https://github.com/adonisjs/env/pull/26

---
Is there a guide/documentation/read/reference on how to do patch fixes on any packages  
For instance, when in Laravel or another frameworks, I can directly go into the vendor/ and make changes to the files until a bug fix is available  
Something similar for node..

**Comment by thetutlage** [comment]
>  I can directly go into the vendor/ and make changes to the files until a bug fix is available

But I think your changes will be lost once you run `composer install` again?

**Comment by thetutlage** [comment]
Release as 3.0.4
